Create SmallestPrime.java
OmarHatem28/SWE-GIT-Assignment pull request #11
Opened 2018-11-28 19:53 UTC by VRanaV

ID 20160309
I am supposed to make the smallest prime function

2018-11-28 20:24 UTC, LinaSabboula requested changes
You're suppose to clone repo from here, create a new branch and make your edits on that branch and call it from the main
add the ==== lines at the end of your function to have a cleaner overall look when executing all functions
No parameters should be passed to function, see the global array and make a copy of it if needed
Function should handle isStringCase (sending back message to user that you cant get prime for a string)
Handling case when there are no prime numbers in array
Test your function well and push again

2018-11-29 19:33 UTC, OmarHatem28 reviewed
1- please add your function case i,e if your function is number 15 in the menu then add case 15: and call your function

2- i don't get what the first if condition in the for loop does ? and isn't 1 a prime number ?

2018-11-29 20:12 UTC, VRanaV commented
no 1 isn't prime and the condition is for 0, 1, 4 which is semi prime to get handled and change the flag .

2018-11-30 11:52 UTC, OmarHatem28 approved these changes

2018-11-30 12:59 UTC, HabibaEsmail approved these changes

2018-11-30 13:07 UTC, LinaSabboula approved these changes

2018-11-30 13:10 UTC, merged